name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.BOT2 }}

  validation_and_merge:
    name: Validation and Merge
    runs-on: ubuntu-latest
    needs:
      - auto-approve
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Octokit in Scripts
        run: npm install @octokit/rest

      - name: Trigger Validation Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOT2 }}
          script: |
            const octokit = require('@octokit/rest')();
            const { data: workflow } = await octokit.request('GET /repos/{owner}/{repo}/actions/workflows/{workflow_file}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: 'validation.yml'
            });
            await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow.id
            });

      - name: Trigger Merge Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOT2 }}
          script: |
            const octokit = require('@octokit/rest')();
            const { data: workflow } = await octokit.request('GET /repos/{owner}/{repo}/actions/workflows/{workflow_file}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: 'merge.yml'
            });
            await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow.id
            });
