name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.BOT2 }}

  merge:
    name: Run Merge.yml
    runs-on: ubuntu-latest
    needs:
      - auto-approve
    steps:
    - name: Trigger Merge Workflow
        run: |
          import { request } from '@octokit/request';
          const { data: workflow } = await request('GET /repos/{owner}/{repo}/actions/workflows/{workflow_file}', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_file: 'merge.yml'
          });
          await request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: workflow.id
          });
