name: Auto Merge

on:
  issue_comment:
    types: [created]
  push:
        branches: [main]
        paths:
            - "domains/**"
            - ".github/workflows/merge.yml"
            - "dnsconfig.js"
  pull_request_target:
    types: [opened,closed,synchronize]

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-validation
  cancel-in-progress: true

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: contributor-assistant/github-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.BOT }}
        with:
          path-to-signatures: 'signatures.json'
          path-to-document: 'https://github.com/is-cool-me/register/blob/main/terms.md' # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: 'main'
          allowlist: icme-bot,bot*
          remote-organization-name: 'is-cool-me'
          remote-repository-name: 'cla'

  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check DNS
        uses: is-cool-me/dnscontrol-action@v4.7.3
        with:
          args: check
          config_file: "dnsconfig.js"

      - name: JSON Syntax Check
        uses: is-cool-me/json-syntax-check@v1
        with:
          pattern: "\\.json$"
        env:
          BASE: "domains/"

  automerge:
    name: Auto Merge
    runs-on: ubuntu-latest
    steps:
      - name: Delay for 20s
        run: sleep 20s

      - name: AutoMerge
        if: github.event_name == 'pull_request_target'
        id: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.BOT }}"
          MERGE_LABELS: ""
