name: Auto Merge

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Delay for 20s
        run: sleep 20s

      - id: automerge
        name: AutoMerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.BOT2 }}"
          MERGE_LABELS: ""
